### ISSUE TITLE
Doesn't work under F24

### ISSUE THREAD

**Issue by fb87** [Rudd-O/zfs-fedora-installer#19]
Now it's the second time I try this and still there's an error which prevents using this. My Fedora is up to date. First I had to install device-mapper-devel for getting around a dependency error, then I get the following output:

```
Installiert:
  ksh.x86_64 20120801-29.fc24              libnvpair1.x86_64 0.7.0-rc1.fc24     
  libuutil1.x86_64 0.7.0-rc1.fc24          libzfs2.x86_64 0.7.0-rc1.fc24        
  libzfs2-devel.x86_64 0.7.0-rc1.fc24      libzpool2.x86_64 0.7.0-rc1.fc24      
  zfs.x86_64 0.7.0-rc1.fc24                zfs-dkms.noarch 0.7.0-rc1.fc24       
  zfs-dracut.x86_64 0.7.0-rc1.fc24        

Komplett!
   ERROR:          root:          deploy_zfs@1231	Unexpected error
Traceback (most recent call last):
  File "./src/installfedoraonzfs/__init__.py", line 1229, in deploy_zfs
    to_unmount=to_unmount,)
  File "./src/installfedoraonzfs/__init__.py", line 1196, in deploy_zfs_in_machine
    raise ZFSBuildFailure("expected to find but could not find module zfs.ko in %s.  Perhaps the ZFS source you used is too old to work with the kernel this program installed?" % modules_dir)
ZFSBuildFailure: expected to find but could not find module zfs.ko in /usr/lib/modules/*/*/zfs.ko.  Perhaps the ZFS source you used is too old to work with the kernel this program installed?
    INFO:          root:          deploy_zfs@1233	Cleaning up now
Traceback (most recent call last):
  File "./deploy-zfs", line 10, in <module>
    sys.exit(installfedoraonzfs.deploy_zfs())
  File "./src/installfedoraonzfs/__init__.py", line 1229, in deploy_zfs
    to_unmount=to_unmount,)
  File "./src/installfedoraonzfs/__init__.py", line 1196, in deploy_zfs_in_machine
    raise ZFSBuildFailure("expected to find but could not find module zfs.ko in %s.  Perhaps the ZFS source you used is too old to work with the kernel this program installed?" % modules_dir)
installfedoraonzfs.ZFSBuildFailure: expected to find but could not find module zfs.ko in /usr/lib/modules/*/*/zfs.ko.  Perhaps the ZFS source you used is too old to work with the kernel this program installed?
```

**Comment by Rudd-O** [comment]
On 11/27/2016 02:57 AM, Frank wrote:
>
> Now it's the second time I try this and still there's an error which
> prevents using this. My Fedora is up to date. First I had to install
> device-mapper-devel for getting around a dependency error, then I get
> the following output:
>

Thanks for the bug report.  I will take a look at this.  Which command
line did you use?  Thank you in advance for the answer.

-- 
    Rudd-O
    http://rudd-o.com/

**Comment by fb87** [comment]
Hi Rudd. I use Terminix with standard Bash under Fedora.

**Comment by Rudd-O** [comment]
On 11/28/2016 09:48 PM, Frank wrote:
>
> Hi Rudd. I use Terminix with standard Bash under Fedora.
>

I need the command line you used.  Thanks.


-- 
    Rudd-O
    http://rudd-o.com/

**Comment by fbruetting** [comment]
Never tried since, that was two years ago…
