### ISSUE TITLE
deploy-zfs: Missing dependencies

### ISSUE THREAD

**Issue by vista-** [Rudd-O/zfs-fedora-installer#25]
I'm using Fedora 27 and I came across this error message when running deploy-zfs:

```
   DEBUG:         shell:          check_call@  27	Check calling bash -c 'cd /usr/src/zfs && ./autogen.sh && ./configure --with-config=user && make -j4 rpm-utils && make -j4 rpm-dkms' in cwd '/home/xxxxxxx/dev/zfs-fedora-installer'
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I config
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
configure.ac:50: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
checking for gawk... gawk
checking metadata... META file
configure: error: cannot find install-sh, install.sh, or shtool in config "."/config
   ERROR:          root:          deploy_zfs@1227	Unexpected error
Traceback (most recent call last):
  File "./src/installfedoraonzfs/__init__.py", line 1225, in deploy_zfs
    to_unmount=to_unmount,)
  File "./src/installfedoraonzfs/__init__.py", line 1182, in deploy_zfs_in_machine
    check_call(cmd)
  File "./src/installfedoraonzfs/cmd.py", line 28, in check_call
    return subprocess.check_call(*args,**kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['bash', '-c', 'cd /usr/src/zfs && ./autogen.sh && ./configure --with-config=user && make -j4 rpm-utils && make -j4 rpm-dkms']' returned non-zero exit status 1
    INFO:          root:          deploy_zfs@1229	Cleaning up now
Traceback (most recent call last):
  File "./deploy-zfs", line 10, in <module>
    sys.exit(installfedoraonzfs.deploy_zfs())
  File "./src/installfedoraonzfs/__init__.py", line 1225, in deploy_zfs
    to_unmount=to_unmount,)
  File "./src/installfedoraonzfs/__init__.py", line 1182, in deploy_zfs_in_machine
    check_call(cmd)
  File "./src/installfedoraonzfs/cmd.py", line 28, in check_call
    return subprocess.check_call(*args,**kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bash', '-c', 'cd /usr/src/zfs && ./autogen.sh && ./configure --with-config=user && make -j4 rpm-utils && make -j4 rpm-dkms']' returned non-zero exit status 1
```

The problem is caused by a missing dependency, `libtool`. After installing it, I ran into another missing dependency problem while configuring ZFS:

```
configure: error: in `/usr/src/zfs':
configure: error: 
	*** evp.h missing, libssl-devel package required
```

Installing `openssl-devel` also solves this problem.

**Comment by vista-** [comment]
Adding `automake` and `libtirpc-devel` to the deps could also be helpful for those who are bootstrapping their system. I'm currently testing on a minimal netinst of Fedora 28.

**Comment by Rudd-O** [comment]
Fixed.
