### ISSUE TITLE
F29 x86_64 QEMU failing with "pkgmgr not defined"

### ISSUE THREAD

**Issue by NeoFromMatrix** [Rudd-O/zfs-fedora-installer#28]
Brand new and updated F29 install in QEMU (Fedora-Workstation-Live-x86_64-29-1.2.iso), produces following error log: 

[root@localhost-live zfs-fedora-installer]# ./deploy-zfs 
    INFO:          root:deploy_zfs_in_machine@1142	Checking if grub-zfs-fixer has the GRUB ZFS fixer installed
   DEBUG:         shell:        check_output@  37	Check outputting rpm -q grub-zfs-fixer-0.0.3-1 in cwd '/usr/src/zfs-fedora-installer'
    INFO:          root:deploy_zfs_in_machine@1155	grub-zfs-fixer does not have the GRUB ZFS fixer, building
    INFO:          root:deploy_zfs_in_machine@1183	Installing built RPMs: ['/usr/src/grub-zfs-fixer/RPMS/noarch/grub-zfs-fixer-0.0.3-1.noarch.rpm']
    INFO:            PM:install_local_packages@ 294	Installing packages ['--downloadonly']: /usr/src/grub-zfs-fixer/RPMS/noarch/grub-zfs-fixer-0.0.3-1.noarch.rpm
   ERROR:          root:          deploy_zfs@1301	Unexpected error
Traceback (most recent call last):
  File "./src/installfedoraonzfs/__init__.py", line 1299, in deploy_zfs
    to_unmount=to_unmount,)
  File "./src/installfedoraonzfs/__init__.py", line 1184, in deploy_zfs_in_machine
    pkgmgr.install_local_packages(files_to_install)
  File "./src/installfedoraonzfs/pm.py", line 300, in install_local_packages
    + packages
NameError: global name 'pkgmgr' is not defined
    INFO:          root:          deploy_zfs@1303	Cleaning up now
Traceback (most recent call last):
  File "./deploy-zfs", line 10, in <module>
    sys.exit(installfedoraonzfs.deploy_zfs())
  File "./src/installfedoraonzfs/__init__.py", line 1299, in deploy_zfs
    to_unmount=to_unmount,)
  File "./src/installfedoraonzfs/__init__.py", line 1184, in deploy_zfs_in_machine
    pkgmgr.install_local_packages(files_to_install)
  File "./src/installfedoraonzfs/pm.py", line 300, in install_local_packages
    + packages
NameError: global name 'pkgmgr' is not defined

Any ideas how to resolve this error?

**Comment by NeoFromMatrix** [comment]
same result with F27 xfce (selinux left at default, enforcing)

**Comment by Rudd-O** [comment]
This is fixed now.
