### ISSUE TITLE
deploy_zfs not executing

### ISSUE THREAD

**Issue by luthepa1** [Rudd-O/zfs-fedora-installer#31]
Hi,

I'm having trouble using this deploy_zfs app that I downloaded from your git repo.  I'm running Fedora 31 desktop.  Its a fairly fresh install.  Not sure if these python scripts still function for Fedora 31?  I will paste my terminal output below fo the errors.  Executing by itself (thus python 2 I would believe) and then executing with python3.  Do you have any ideas?  Hopefully its not a newb thing on my part but could be.

Many thanks,

Paul.

`[luthepa1@z77x zfs-fedora-installer-master]$ python3 ./deploy-zfs 
Traceback (most recent call last):
  File "./deploy-zfs", line 6, in <module>
    import installfedoraonzfs
  File "./src/installfedoraonzfs/__init__.py", line 237
    except OSError, e:
                  ^
SyntaxError: invalid syntax
[luthepa1@z77x zfs-fedora-installer-master]$  ./deploy-zfs 
Traceback (most recent call last):
  File "./deploy-zfs", line 10, in <module>
    sys.exit(installfedoraonzfs.deploy_zfs())
  File "./src/installfedoraonzfs/__init__.py", line 1446, in deploy_zfs
    pkgmgr = SystemPackageManager()
  File "./src/installfedoraonzfs/pm.py", line 290, in __init__
    BasePackageManager.__init__(self)
  File "./src/installfedoraonzfs/pm.py", line 107, in __init__
    self.myreleasever = self.get_my_releasever()
  File "./src/installfedoraonzfs/pm.py", line 111, in get_my_releasever
    return int(check_output(["rpm", "-q", "fedora-release", "--queryformat=%{version}"]))
  File "./src/installfedoraonzfs/cmd.py", line 41, in check_output
    output = subprocess.check_output(*args,**kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['rpm', '-q', 'fedora-release', '--queryformat=%{version}']' returned non-zero exit status 1
[luthepa1@z77x zfs-fedora-installer-master]$ 
`

`[luthepa1@z77x mnt]$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 31 (Thirty One)
Release:	31
Codename:	ThirtyOne
`

**Comment by Rudd-O** [comment]
Deffo a bug in the code not being written for Python 3.  Either install Python 2 or run the code thru `2to3` and send me a PR to merge.  Thanks.
